// AUTO-GENERATED by `supabase gen types typescript` (via Supabase MCP).
// Do not edit by hand — re-run generation after schema changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      admins: {
        Row: { added_at: string; user_id: string }
        Insert: { added_at?: string; user_id: string }
        Update: { added_at?: string; user_id?: string }
        Relationships: []
      }
      branding: {
        Row: {
          accent_color: string | null
          bride_name: string | null
          cover_photo: string | null
          event_id: string
          greeting_text: string | null
          groom_name: string | null
          updated_at: string
        }
        Insert: {
          accent_color?: string | null
          bride_name?: string | null
          cover_photo?: string | null
          event_id: string
          greeting_text?: string | null
          groom_name?: string | null
          updated_at?: string
        }
        Update: {
          accent_color?: string | null
          bride_name?: string | null
          cover_photo?: string | null
          event_id?: string
          greeting_text?: string | null
          groom_name?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "branding_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: true
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
        ]
      }
      events: {
        Row: {
          archive_expires_at: string | null
          couple_names: string
          created_at: string
          geofence_radius: number | null
          id: string
          owner_id: string | null
          plan_tier: string | null
          qr_pdf_path: string | null
          status: string
          table_count: number | null
          updated_at: string
          venue_lat: number | null
          venue_lng: number | null
          venue_name: string | null
          wedding_date: string
        }
        Insert: {
          archive_expires_at?: string | null
          couple_names: string
          created_at?: string
          geofence_radius?: number | null
          id?: string
          owner_id?: string | null
          plan_tier?: string | null
          qr_pdf_path?: string | null
          status?: string
          table_count?: number | null
          updated_at?: string
          venue_lat?: number | null
          venue_lng?: number | null
          venue_name?: string | null
          wedding_date: string
        }
        Update: {
          archive_expires_at?: string | null
          couple_names?: string
          created_at?: string
          geofence_radius?: number | null
          id?: string
          owner_id?: string | null
          plan_tier?: string | null
          qr_pdf_path?: string | null
          status?: string
          table_count?: number | null
          updated_at?: string
          venue_lat?: number | null
          venue_lng?: number | null
          venue_name?: string | null
          wedding_date?: string
        }
        Relationships: []
      }
      leads: {
        Row: {
          created_at: string
          guests_estimate: number | null
          id: string
          locale: string | null
          name: string
          phone: string
          source: string | null
          wedding_date: string | null
        }
        Insert: {
          created_at?: string
          guests_estimate?: number | null
          id?: string
          locale?: string | null
          name: string
          phone: string
          source?: string | null
          wedding_date?: string | null
        }
        Update: {
          created_at?: string
          guests_estimate?: number | null
          id?: string
          locale?: string | null
          name?: string
          phone?: string
          source?: string | null
          wedding_date?: string | null
        }
        Relationships: []
      }
      photos: {
        Row: {
          event_id: string
          guest_name: string | null
          guest_table: number | null
          id: string
          is_hidden: boolean
          is_highlight: boolean
          mime_type: string | null
          size_bytes: number | null
          storage_path: string
          thumbnail_path: string | null
          uploaded_at: string
        }
        Insert: {
          event_id: string
          guest_name?: string | null
          guest_table?: number | null
          id?: string
          is_hidden?: boolean
          is_highlight?: boolean
          mime_type?: string | null
          size_bytes?: number | null
          storage_path: string
          thumbnail_path?: string | null
          uploaded_at?: string
        }
        Update: {
          event_id?: string
          guest_name?: string | null
          guest_table?: number | null
          id?: string
          is_hidden?: boolean
          is_highlight?: boolean
          mime_type?: string | null
          size_bytes?: number | null
          storage_path?: string
          thumbnail_path?: string | null
          uploaded_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "photos_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
        ]
      }
      referral_attributions: {
        Row: {
          attributed_at: string
          event_id: string | null
          id: string
          lead_id: string | null
          referral_id: string
        }
        Insert: {
          attributed_at?: string
          event_id?: string | null
          id?: string
          lead_id?: string | null
          referral_id: string
        }
        Update: {
          attributed_at?: string
          event_id?: string | null
          id?: string
          lead_id?: string | null
          referral_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "referral_attributions_event_id_fkey"
            columns: ["event_id"]
            isOneToOne: false
            referencedRelation: "events"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "referral_attributions_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "referral_attributions_referral_id_fkey"
            columns: ["referral_id"]
            isOneToOne: false
            referencedRelation: "referrals"
            referencedColumns: ["id"]
          },
        ]
      }
      referrals: {
        Row: {
          code: string
          commission_pct: number | null
          created_at: string
          id: string
          partner_name: string | null
          partner_phone: string | null
        }
        Insert: {
          code: string
          commission_pct?: number | null
          created_at?: string
          id?: string
          partner_name?: string | null
          partner_phone?: string | null
        }
        Update: {
          code?: string
          commission_pct?: number | null
          created_at?: string
          id?: string
          partner_name?: string | null
          partner_phone?: string | null
        }
        Relationships: []
      }
    }
    Views: { [_ in never]: never }
    Functions: { [_ in never]: never }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}
