// AUTO-GENERATED by `supabase gen types typescript` (via Supabase MCP).
// Do not edit by hand — re-run generation after schema changes.

export type Json
  = | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export interface Database {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '14.5'
  }
  public: {
    Tables: {
      admin_otps: {
        Row: {
          attempts: number
          code_hash: string
          consumed_at: string | null
          created_at: string
          email: string
          expires_at: string
          ip: string | null
          user_agent: string | null
        }
        Insert: {
          attempts?: number
          code_hash: string
          consumed_at?: string | null
          created_at?: string
          email: string
          expires_at: string
          ip?: string | null
          user_agent?: string | null
        }
        Update: {
          attempts?: number
          code_hash?: string
          consumed_at?: string | null
          created_at?: string
          email?: string
          expires_at?: string
          ip?: string | null
          user_agent?: string | null
        }
        Relationships: []
      }
      admins: {
        Row: {
          added_at: string
          role: string
          telegram_chat_id: string | null
          user_id: string
        }
        Insert: {
          added_at?: string
          role?: string
          telegram_chat_id?: string | null
          user_id: string
        }
        Update: {
          added_at?: string
          role?: string
          telegram_chat_id?: string | null
          user_id?: string
        }
        Relationships: []
      }
      branding: {
        Row: {
          accent_color: string | null
          bride_name: string | null
          cover_photo: string | null
          event_id: string
          greeting_text: string | null
          groom_name: string | null
          updated_at: string
        }
        Insert: {
          accent_color?: string | null
          bride_name?: string | null
          cover_photo?: string | null
          event_id: string
          greeting_text?: string | null
          groom_name?: string | null
          updated_at?: string
        }
        Update: {
          accent_color?: string | null
          bride_name?: string | null
          cover_photo?: string | null
          event_id?: string
          greeting_text?: string | null
          groom_name?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'branding_event_id_fkey'
            columns: ['event_id']
            isOneToOne: true
            referencedRelation: 'events'
            referencedColumns: ['id']
          },
        ]
      }
      events: {
        Row: {
          archive_expires_at: string | null
          couple_names: string
          created_at: string
          geofence_radius: number | null
          id: string
          owner_id: string | null
          owner_phone: string | null
          plan_tier: string | null
          qr_pdf_path: string | null
          qr_settings: Json
          status: string
          table_count: number | null
          updated_at: string
          venue_lat: number | null
          venue_lng: number | null
          venue_name: string | null
          wedding_date: string
        }
        Insert: {
          archive_expires_at?: string | null
          couple_names: string
          created_at?: string
          geofence_radius?: number | null
          id?: string
          owner_id?: string | null
          owner_phone?: string | null
          plan_tier?: string | null
          qr_pdf_path?: string | null
          qr_settings?: Json
          status?: string
          table_count?: number | null
          updated_at?: string
          venue_lat?: number | null
          venue_lng?: number | null
          venue_name?: string | null
          wedding_date: string
        }
        Update: {
          archive_expires_at?: string | null
          couple_names?: string
          created_at?: string
          geofence_radius?: number | null
          id?: string
          owner_id?: string | null
          owner_phone?: string | null
          plan_tier?: string | null
          qr_pdf_path?: string | null
          qr_settings?: Json
          status?: string
          table_count?: number | null
          updated_at?: string
          venue_lat?: number | null
          venue_lng?: number | null
          venue_name?: string | null
          wedding_date?: string
        }
        Relationships: []
      }
      guest_devices: {
        Row: {
          device_id: string
          event_id: string
          first_seen_at: string
          guest_name: string | null
          last_seen_at: string
          photo_count: number
          table_number: number
          video_count: number
          voice_count: number
        }
        Insert: {
          device_id: string
          event_id: string
          first_seen_at?: string
          guest_name?: string | null
          last_seen_at?: string
          photo_count?: number
          table_number: number
          video_count?: number
          voice_count?: number
        }
        Update: {
          device_id?: string
          event_id?: string
          first_seen_at?: string
          guest_name?: string | null
          last_seen_at?: string
          photo_count?: number
          table_number?: number
          video_count?: number
          voice_count?: number
        }
        Relationships: [
          {
            foreignKeyName: 'guest_devices_event_id_fkey'
            columns: ['event_id']
            isOneToOne: false
            referencedRelation: 'events'
            referencedColumns: ['id']
          },
        ]
      }
      leads: {
        Row: {
          converted_event_id: string | null
          created_at: string
          guests_estimate: number | null
          id: string
          locale: string | null
          name: string
          notes: string | null
          phone: string
          source: string | null
          status: string
          wedding_date: string | null
        }
        Insert: {
          converted_event_id?: string | null
          created_at?: string
          guests_estimate?: number | null
          id?: string
          locale?: string | null
          name: string
          notes?: string | null
          phone: string
          source?: string | null
          status?: string
          wedding_date?: string | null
        }
        Update: {
          converted_event_id?: string | null
          created_at?: string
          guests_estimate?: number | null
          id?: string
          locale?: string | null
          name?: string
          notes?: string | null
          phone?: string
          source?: string | null
          status?: string
          wedding_date?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'leads_converted_event_id_fkey'
            columns: ['converted_event_id']
            isOneToOne: false
            referencedRelation: 'events'
            referencedColumns: ['id']
          },
        ]
      }
      payments: {
        Row: {
          amount: number
          created_at: string
          currency: string
          event_id: string
          id: string
          metadata: Json | null
          provider: string
          provider_transaction_id: string | null
          status: string
          updated_at: string
        }
        Insert: {
          amount: number
          created_at?: string
          currency?: string
          event_id: string
          id?: string
          metadata?: Json | null
          provider: string
          provider_transaction_id?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          amount?: number
          created_at?: string
          currency?: string
          event_id?: string
          id?: string
          metadata?: Json | null
          provider?: string
          provider_transaction_id?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'payments_event_id_fkey'
            columns: ['event_id']
            isOneToOne: false
            referencedRelation: 'events'
            referencedColumns: ['id']
          },
        ]
      }
      phone_otps: {
        Row: {
          attempts: number
          code_hash: string
          consumed_at: string | null
          created_at: string
          expires_at: string
          ip: string | null
          phone: string
          user_agent: string | null
        }
        Insert: {
          attempts?: number
          code_hash: string
          consumed_at?: string | null
          created_at?: string
          expires_at: string
          ip?: string | null
          phone: string
          user_agent?: string | null
        }
        Update: {
          attempts?: number
          code_hash?: string
          consumed_at?: string | null
          created_at?: string
          expires_at?: string
          ip?: string | null
          phone?: string
          user_agent?: string | null
        }
        Relationships: []
      }
      photos: {
        Row: {
          duration_ms: number | null
          event_id: string
          guest_name: string | null
          guest_table: number | null
          id: string
          is_hidden: boolean
          is_highlight: boolean
          media_type: string
          mime_type: string | null
          size_bytes: number | null
          storage_path: string
          thumbnail_path: string | null
          uploaded_at: string
        }
        Insert: {
          duration_ms?: number | null
          event_id: string
          guest_name?: string | null
          guest_table?: number | null
          id?: string
          is_hidden?: boolean
          is_highlight?: boolean
          media_type?: string
          mime_type?: string | null
          size_bytes?: number | null
          storage_path: string
          thumbnail_path?: string | null
          uploaded_at?: string
        }
        Update: {
          duration_ms?: number | null
          event_id?: string
          guest_name?: string | null
          guest_table?: number | null
          id?: string
          is_hidden?: boolean
          is_highlight?: boolean
          media_type?: string
          mime_type?: string | null
          size_bytes?: number | null
          storage_path?: string
          thumbnail_path?: string | null
          uploaded_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'photos_event_id_fkey'
            columns: ['event_id']
            isOneToOne: false
            referencedRelation: 'events'
            referencedColumns: ['id']
          },
        ]
      }
      referral_attributions: {
        Row: {
          attributed_at: string
          event_id: string | null
          id: string
          lead_id: string | null
          referral_id: string
        }
        Insert: {
          attributed_at?: string
          event_id?: string | null
          id?: string
          lead_id?: string | null
          referral_id: string
        }
        Update: {
          attributed_at?: string
          event_id?: string | null
          id?: string
          lead_id?: string | null
          referral_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'referral_attributions_event_id_fkey'
            columns: ['event_id']
            isOneToOne: false
            referencedRelation: 'events'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'referral_attributions_lead_id_fkey'
            columns: ['lead_id']
            isOneToOne: false
            referencedRelation: 'leads'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'referral_attributions_referral_id_fkey'
            columns: ['referral_id']
            isOneToOne: false
            referencedRelation: 'referrals'
            referencedColumns: ['id']
          },
        ]
      }
      referrals: {
        Row: {
          code: string
          commission_pct: number | null
          created_at: string
          id: string
          partner_name: string | null
          partner_phone: string | null
        }
        Insert: {
          code: string
          commission_pct?: number | null
          created_at?: string
          id?: string
          partner_name?: string | null
          partner_phone?: string | null
        }
        Update: {
          code?: string
          commission_pct?: number | null
          created_at?: string
          id?: string
          partner_name?: string | null
          partner_phone?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      archive_expired_events: { Args: never, Returns: undefined }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
  | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
  | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
      & DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    & DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R
    }
      ? R
      : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables']
    & DefaultSchema['Views'])
    ? (DefaultSchema['Tables']
      & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
        ? R
        : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
  | keyof DefaultSchema['Tables']
  | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
    Insert: infer I
  }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
      Insert: infer I
    }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
  | keyof DefaultSchema['Tables']
  | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
    Update: infer U
  }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
      Update: infer U
    }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
  | keyof DefaultSchema['Enums']
  | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
  | keyof DefaultSchema['CompositeTypes']
  | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
